name: Test and Build

on:
  push:
    branches:
      - master
    paths:
      - '**/*'

permissions:
  contents: write  # Allow pushing changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setting up environment
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          
      # Test the Code
      - name: Run Linting tests
        run: |
          flake8 --ignore=E501,F401 .
      
      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker tag
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build . -t manmathan/weather:${{ env.VERSION }} 
      
      # Push the Docker Image
      - name: Push Docker Image
        run: |
          docker push manmathan/weather:${{ env.VERSION }}
      
      # Update the K8s Manifest Files
      - name: Update K8s Manifests
        run: |
          sed -i "s|image: manmathan/weather:.*|image: manmathan/weather:${{ env.VERSION }}|g" deploy/deploy.yaml
          cat deploy/deploy.yaml

      # Commit and push changes
      - name: Commit the changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add deploy/deploy.yaml
          git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}" || echo "No changes to commit"
          git push origin master
